### ISSUE TITLE
Docs load very slow

### ISSUE THREAD

**Issue by 15astro** [nosqlbench/nosqlbench-docs#1]
I have been using http://docs.nosqlbench.io since the last 3-4 days. The docs load very slow.

It sometimes takes 2 mins, 3 mins or forever loading the docs pages.

**Comment by jshook** [comment]
This is probably related ot how the docs site works, in that it may need to fetch refreshed content for rendering the menu, etc. There are some specific improvements we can make to avoid the round-tripping effect.

If you get a chance, can use use the developer/network settings under chrome or something similar to give us an idea about where the loading time is for you?

**Comment by 15astro** [comment]
Here is the sample error while loading Portable Workloads page:
http://docs.nosqlbench.io/#/docs/showcase%2Fportable_workloads

![image](https://user-images.githubusercontent.com/17779264/81421643-63347100-916f-11ea-887e-d561b9333a9a.png)

**Comment by jshook** [comment]
This is helpful.
From those errors it seems that we should reduce reliance on any external fonts, etc.

Just to make sure you are aware, You can run the docs in local mode with `nb docserver` or `java -jar nb.jar docserver` as well. This won't solve issues with loading fonts remotely, but it might improve overall response for docs in general.

**Comment by jshook** [comment]
This should be very improved. The content for each page should be cached on the client due to some changes in the loading logic.
